### ISSUE TITLE
x64 version crashes for nsteps > 6

### ISSUE THREAD

**Issue by LigH-de** [HomeOfAviSynthPlusEvolution/neo_Vague_Denoiser#7]
Processing 1920×800 px video in AviSynth+ with multithreading, `neo_vd(nsteps=7)` crashes VirtualDub2 x64 (it simply closes without any error message), while VirtualDub2 x86 runs with `neo_vd(nsteps=9)`.

**Comment by Asd-g** [comment]
Can you try with different `opt` values?

**Comment by LigH-de** [comment]
Yesterday it crashed reliably, tested half a dozen times. Today it does not crash anymore... 🤔
